NJU-ProjectN/abstract-machine ics2024 initialized
NJU-ProjectN/abstract-machine 878e63dc3bf1c451b396c27ebc630a2a713d606c tools,minirv: fix unexpected instruction replacement

diff --git a/npc/Makefile b/npc/Makefile
--- a/npc/Makefile
+++ b/npc/Makefile
@@ -48,6 +48,13 @@ sim: $(BIN)
 	@echo "Running simulation with git commit..."
 	./build/top +trace  
 
+run: $(BIN)
+	@if [ -z "$(IMAGE)" ];then \
+		echo "Error: 请通过 'IMAGE=xxx.bin' 指定镜像文件路径new"; \
+		exit 1;\
+	fi
+	./$(BIN) $(IMAGE) +trace
+	
 clean:
 	rm -rf $(BUILD_DIR) wave.vcd
 
